// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	link "app/internal/domain/link"
	service "app/internal/service"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShortURL is a mock of ShortURL interface.
type MockShortURL struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLMockRecorder
	isgomock struct{}
}

// MockShortURLMockRecorder is the mock recorder for MockShortURL.
type MockShortURLMockRecorder struct {
	mock *MockShortURL
}

// NewMockShortURL creates a new mock instance.
func NewMockShortURL(ctrl *gomock.Controller) *MockShortURL {
	mock := &MockShortURL{ctrl: ctrl}
	mock.recorder = &MockShortURLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURL) EXPECT() *MockShortURLMockRecorder {
	return m.recorder
}

// FindURL mocks base method.
func (m *MockShortURL) FindURL(ctx context.Context, id string) (link.ExpandedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindURL", ctx, id)
	ret0, _ := ret[0].(link.ExpandedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindURL indicates an expected call of FindURL.
func (mr *MockShortURLMockRecorder) FindURL(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindURL", reflect.TypeOf((*MockShortURL)(nil).FindURL), ctx, id)
}

// FormatShortURL mocks base method.
func (m *MockShortURL) FormatShortURL(urlID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatShortURL", urlID)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatShortURL indicates an expected call of FormatShortURL.
func (mr *MockShortURLMockRecorder) FormatShortURL(urlID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatShortURL", reflect.TypeOf((*MockShortURL)(nil).FormatShortURL), urlID)
}

// ShortenBatch mocks base method.
func (m *MockShortURL) ShortenBatch(ctx context.Context, batch []service.BatchInput) ([]link.ExpandedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenBatch", ctx, batch)
	ret0, _ := ret[0].([]link.ExpandedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenBatch indicates an expected call of ShortenBatch.
func (mr *MockShortURLMockRecorder) ShortenBatch(ctx, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenBatch", reflect.TypeOf((*MockShortURL)(nil).ShortenBatch), ctx, batch)
}

// ShortenURL mocks base method.
func (m *MockShortURL) ShortenURL(ctx context.Context, url string) (link.ExpandedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenURL", ctx, url)
	ret0, _ := ret[0].(link.ExpandedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenURL indicates an expected call of ShortenURL.
func (mr *MockShortURLMockRecorder) ShortenURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenURL", reflect.TypeOf((*MockShortURL)(nil).ShortenURL), ctx, url)
}

// MockPinger is a mock of Pinger interface.
type MockPinger struct {
	ctrl     *gomock.Controller
	recorder *MockPingerMockRecorder
	isgomock struct{}
}

// MockPingerMockRecorder is the mock recorder for MockPinger.
type MockPingerMockRecorder struct {
	mock *MockPinger
}

// NewMockPinger creates a new mock instance.
func NewMockPinger(ctrl *gomock.Controller) *MockPinger {
	mock := &MockPinger{ctrl: ctrl}
	mock.recorder = &MockPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinger) EXPECT() *MockPingerMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockPinger) CheckHealth(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockPingerMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockPinger)(nil).CheckHealth), ctx)
}
